local M = {}

local function highlight(group, guifg, guibg, attr, guisp)
  local parts = { group }

  if guifg then table.insert(parts, "guifg=" .. guifg) end
  if guibg then table.insert(parts, "guibg=" .. guibg) end
  if attr then table.insert(parts, "gui=" .. attr) end
  if guisp then table.insert(parts, "guisp=" .. guisp) end

  vim.api.nvim_command("highlight " .. table.concat(parts, " "))
end

M.get = {
  white = "#F8F8F2",
  white2 = "#f7f7fb",
  light_white = "#E9E9f4",
  darker_black = "#232531",
  black = "#282A36",
  black2 = "#303341",
  black3 = "#3a3c4e",
  grey = "#41434f",
  grey2 = "#44475a",
  grey3 = "#232531",
  grey_fg = "#5a5c68",
  light_grey = "#6272a4",
  red = "#E95678",
  pink = "#FF79C6",
  light_pink = "#ff92df",
  green = "#69ff94",
  yellow = "#F1FA8C",
  light_yellow = "#ffffa5";
  purple = "#BD93F9",
  cyan = "#8BE9FD",
  orange = "#ffB86C",
}

M.apply = function ()
  local colors = M.get
  vim.cmd "hi clear CursorLine"

  highlight("Normal", colors.light_white, colors.black, nil, nil)
  highlight("Bold", nil, nil, "bold", nil)
  highlight("Debug", colors.orange, nil, nil, nil)
  highlight("Directory", colors.green, nil, nil, nil)
  highlight("Error", colors.black, colors.orange, nil, nil)
  highlight("ErrorMsg", colors.orange, colors.black, nil, nil)
  highlight("Exception", colors.orange, nil, nil, nil)
  highlight("FoldColumn", colors.cyan, colors.black3, nil, nil)
  highlight("Folded", colors.light_grey, colors.black3, nil, nil)
  highlight("IncSearch", colors.black3, colors.purple, "none", nil)
  highlight("Italic", nil, nil, "none", nil)
  highlight("Macro", colors.orange, nil, nil, nil)
  highlight("MatchParen", nil, colors.light_grey, nil, nil)
  highlight("ModeMsg", colors.light_yellow, nil, nil, nil)
  highlight("MoreMsg", colors.light_yellow, nil, nil, nil)
  highlight("Question", colors.green, nil, nil, nil)
  highlight("Search", colors.black3, colors.cyan, nil, nil)
  highlight("Substitute", colors.black3, colors.cyan, "none", nil)
  highlight("SpecialKey", colors.light_grey, nil, nil, nil)
  highlight("TooLong", colors.orange, nil, nil, nil)
  highlight("Underlined", colors.orange, nil, nil, nil)
  highlight("Visual", nil, colors.grey2, nil, nil)
  highlight("VisualNOS", colors.orange, nil, nil, nil)
  highlight("WarningMsg", colors.orange, nil, nil, nil)
  highlight("WildMenu", colors.orange, colors.cyan, nil, nil)
  highlight("Title", colors.green, nil, "none", nil)
  highlight("Conceal", colors.green, colors.black, nil, nil)
  highlight("NonText", colors.light_grey, nil, nil, nil)
  highlight("QuickFixLine", nil, colors.black3, "none", nil)
  highlight("StatusLine", '#62d6e8', "NONE", "none", nil)
  highlight("StatusLineNC", colors.light_grey, "NONE", "none", nil)
  highlight("SignColumn", colors.light_grey, "NONE", nil, nil)
  highlight("VertSplit", colors.grey2, "NONE", "none", nil)
  highlight("ColorColumn", nil, colors.black3, "none", nil)
  highlight("LineNr", colors.grey, "none", nil, nil)
  highlight("CursorColumn", nil, 'none', "none", nil)
  highlight("CursorLineNr", colors.white, "none", nil, nil)
  highlight("Cursor", colors.black, colors.light_white, nil, nil)
  highlight("FloatBorder", colors.purple, nil, nil, nil)
  highlight("NormalFloat", colors.white, nil, nil, nil)
  highlight("Pmenu", colors.light_white, colors.grey3, 'none', nil)
  highlight("PmenuSel", colors.white, colors.grey2, nil, nil)
  highlight("PmenuSbar", nil, colors.grey3, nil, nil)
  highlight("PmenuThumb", nil, colors.purple, nil, nil)
  highlight("CmpItemAbbr", colors.white, nil, nil, nil)
  highlight("CmpItemAbbrMatch", colors.cyan, nil, nil, nil)
  highlight("CmpItemMenu", colors.white, nil, nil, nil)
  highlight("CmpItemKind", colors.green, nil, nil, nil)
  highlight("CmpItemKindText", colors.white, nil, nil, nil)
  highlight("IndentBlanklineChar", '#373844', nil, nil, nil)
  highlight("NvimTreeNormal", colors.white, colors.grey3, nil, nil)
  highlight("NvimTreeVertSplit", colors.grey3, colors.grey3, nil, nil)
  highlight("NvimTreeGitDirty", colors.yellow, nil, nil, nil)
  highlight("NvimTreeGitNew", colors.green, nil, nil, nil)
  highlight("NvimTreeImageFile", colors.pink, nil, nil, nil)
  highlight("NvimTreeFolderIcon", colors.purple, nil, nil, nil)
  highlight("NvimTreeEmptyFolderName", colors.light_grey, nil, nil, nil)
  highlight("NvimTreeFolderName", colors.purple, nil, nil, nil)
  highlight("NvimTreeOpenedFolderName", colors.green, nil, nil, nil)
  highlight("NvimTreeCursorLine", nil, 'none', nil, nil)
  highlight("NvimTreeIn", nil, colors.grey2, nil, nil)
  highlight("NvimTreeSpecialFile", colors.orange, nil, 'underline', nil)
  highlight("NvimTreeIndentMarker", colors.grey2, nil, nil, nil)
  highlight("NvimTreeRootFolder", colors.green, nil, 'bold', nil)
  highlight("NvimTreeWindowPicker", colors.purple, colors.black2, nil, nil)
  highlight("NvimTreeNormalNC", nil, colors.grey3, nil, nil)
  highlight("NvimTreeStatuslineNc", colors.grey3, colors.grey3, nil, nil)
  highlight("NvimTreeStatusline", colors.grey3, colors.grey3, nil, nil)
  highlight("EndOfBuffer", colors.black, nil, nil, nil)
  highlight("NvimTreeEndOfBuffer", colors.grey3, nil, nil, nil)
  highlight("LspDiagnosticsSignError", colors.red, nil, nil, nil)
  highlight("LspDiagnosticsSignWarning", colors.yellow, nil, nil, nil)
  highlight("LspDiagnosticsSignInformation", colors.green, nil, nil, nil)
  highlight("LspDiagnosticsSignHint", colors.purple, nil, nil, nil)
  highlight("LspDiagnosticsVirtualTextError", colors.red, nil, nil, nil)
  highlight("LspDiagnosticsVirtualTextWarning", colors.yellow, nil, nil, nil)
  highlight("LspDiagnosticsVirtualTextInformation", colors.green, nil, nil, nil)
  highlight("LspDiagnosticsVirtualTextHint", colors.purple, nil, nil, nil)
  highlight("TabLine", colors.light_grey, colors.black3, "none", nil)
  highlight("TabLineFill", colors.light_grey, colors.black3, "none", nil)
  highlight("TabLineSel", colors.light_yellow, colors.black3, "none", nil)
  highlight("Boolean", colors.purple, nil, nil, nil)
  highlight("Character", colors.orange, nil, nil, nil)
  highlight("Comment", colors.light_grey, nil, nil, nil)
  highlight("Conditional", colors.light_pink, nil, nil, nil)
  highlight("Constant", colors.purple, nil, nil, nil)
  highlight("Define", colors.light_pink, nil, "none", nil)
  highlight("Delimiter", colors.white2, nil, nil, nil)
  highlight("Float", colors.purple, nil, nil, nil)
  highlight("Function", colors.green, nil, nil, nil)
  highlight("Identifier", colors.orange, nil, "none", nil)
  highlight("Include", colors.green, nil, nil, nil)
  highlight("Keyword", colors.light_pink, nil, nil, nil)
  highlight("Label", colors.cyan, nil, nil, nil)
  highlight("Number", colors.purple, nil, nil, nil)
  highlight("Operator", colors.light_white, nil, "none", nil)
  highlight("PreProc", colors.cyan, nil, nil, nil)
  highlight("Repeat", colors.cyan, nil, nil, nil)
  highlight("Special", colors.cyan, nil, nil, nil)
  highlight("SpecialChar", colors.white2, nil, nil, nil)
  highlight("Statement", colors.orange, nil, nil, nil)
  highlight("StorageClass", colors.cyan, nil, nil, nil)
  highlight("String", colors.light_yellow, nil, nil, nil)
  highlight("Structure", colors.light_pink, nil, nil, nil)
  highlight("Tag", colors.cyan, nil, nil, nil)
  highlight("Todo", colors.cyan, colors.black3, nil, nil)
  highlight("Type", colors.cyan, nil, "none", nil)
  highlight("Typedef", colors.cyan, nil, nil, nil)
  highlight("cssBraces", colors.light_white, nil, nil, nil)
  highlight("cssClassName", colors.light_pink, nil, nil, nil)
  highlight("cssColor", colors.cyan, nil, nil, nil)
  highlight("DiffAdd", colors.purple, 'none', nil, nil)
  highlight("DiffChange", '#5a5c68', 'none', nil, nil)
  highlight("DiffDelete", colors.red, 'none', nil, nil)
  highlight("DiffText", colors.green, colors.black3, nil, nil)
  highlight("gitcommitOverflow", colors.orange, nil, nil, nil)
  highlight("gitcommitSummary", colors.light_yellow, nil, nil, nil)
  highlight("gitcommitComment", colors.light_grey, nil, nil, nil)
  highlight("gitcommitUntracked", colors.light_grey, nil, nil, nil)
  highlight("gitcommitDiscarded", colors.light_grey, nil, nil, nil)
  highlight("gitcommitSelected", colors.light_grey, nil, nil, nil)
  highlight("gitcommitHeader", colors.light_pink, nil, nil, nil)
  highlight("gitcommitSelectedType", colors.green, nil, nil, nil)
  highlight("gitcommitUnmergedType", colors.green, nil, nil, nil)
  highlight("gitcommitDiscardedType", colors.green, nil, nil, nil)
  highlight("gitcommitBranch", colors.purple, nil, "bold", nil)
  highlight("gitcommitUntrackedFile", colors.cyan, nil, nil, nil)
  highlight("gitcommitUnmergedFile", colors.orange, nil, "bold", nil)
  highlight("gitcommitDiscardedFile", colors.orange, nil, "bold", nil)
  highlight("gitcommitSelectedFile", colors.light_yellow, nil, "bold", nil)
  highlight("htmlBold", colors.cyan, nil, nil, nil)
  highlight("htmlItalic", colors.light_pink, nil, nil, nil)
  highlight("htmlEndTag", colors.light_white, nil, nil, nil)
  highlight("htmlTag", colors.light_white, nil, nil, nil)
  highlight("javaScript", colors.light_white, nil, nil, nil)
  highlight("javaScriptBraces", colors.light_white, nil, nil, nil)
  highlight("javaScriptNumber", colors.purple, nil, nil, nil)
  highlight("jsOperator", colors.green, nil, nil, nil)
  highlight("jsStatement", colors.light_pink, nil, nil, nil)
  highlight("jsReturn", colors.light_pink, nil, nil, nil)
  highlight("jsThis", colors.orange, nil, nil, nil)
  highlight("jsClassDefinition", colors.cyan, nil, nil, nil)
  highlight("jsFunction", colors.light_pink, nil, nil, nil)
  highlight("jsFuncName", colors.green, nil, nil, nil)
  highlight("jsFuncCall", colors.green, nil, nil, nil)
  highlight("jsClassFuncName", colors.green, nil, nil, nil)
  highlight("jsClassMethodType", colors.light_pink, nil, nil, nil)
  highlight("jsRegexpString", colors.cyan, nil, nil, nil)
  highlight("jsGlobalObjects", colors.cyan, nil, nil, nil)
  highlight("jsGlobalNodeObjects", colors.cyan, nil, nil, nil)
  highlight("jsExceptions", colors.cyan, nil, nil, nil)
  highlight("jsBuiltins", colors.cyan, nil, nil, nil)
  highlight("markdownCode", colors.light_yellow, nil, nil, nil)
  highlight("markdownError", colors.light_white, colors.black, nil, nil)
  highlight("markdownCodeBlock", colors.light_yellow, nil, nil, nil)
  highlight("markdownHeadingDelimiter", colors.green, nil, nil, nil)
  highlight("pythonOperator", colors.light_pink, nil, nil, nil)
  highlight("pythonRepeat", colors.light_pink, nil, nil, nil)
  highlight("pythonInclude", colors.light_pink, nil, nil, nil)
  highlight("pythonStatement", colors.light_pink, nil, nil, nil)
  highlight("sassidChar", colors.orange, nil, nil, nil)
  highlight("sassClassChar", colors.purple, nil, nil, nil)
  highlight("sassInclude", colors.light_pink, nil, nil, nil)
  highlight("sassMixing", colors.light_pink, nil, nil, nil)
  highlight("sassMixinName", colors.green, nil, nil, nil)
  highlight("LspDiagnosticsDefaultError", colors.orange, nil, nil, nil)
  highlight("LspDiagnosticsDefaultWarning", colors.cyan, nil, nil, nil)
  highlight("LspDiagnosticsDefaultInformation", colors.green, nil, nil, nil)
  highlight("LspDiagnosticsDefaultHint", colors.cyan, nil, nil, nil)
end

return M
